export enum CodeEnum {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_VERIFICATION_REQUIRED = 'EMAIL_VERIFICATION_REQUIRED',
  INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  USER_REGISTERED_SUCCESSFULLY = 'USER_REGISTERED_SUCCESSFULLY',
  VERIFICATION_EMAIL_SENT = 'VERIFICATION_EMAIL_SENT',
  POST_CREATION_FAILED = 'POST_CREATION_FAILED',
  POSTS_FETCH_FAILED = 'POSTS_FETCH_FAILED',
  USER_POSTS_FETCH_FAILED = 'USER_POSTS_FETCH_FAILED',
}

